sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t ratheeshkm/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ratheeshkm/docker-react-app npm run test