version: "3.5"
services:
    app:
        build: ./
        ports:
            - 80:3000
        volumes:
            - ./:/usr/src/
            - /usr/src/node_modules
        # Required for serve React application
        stdin_open: true